* Executive Council

** Order of Election

The executive council consists of the President, Vice President, Treasurer, Recording Secretary, Corresponding Secretary, Department Relations, and Alumni Relations. Other officers may be elected to meet the Chapter’s needs.

** Order of Succession

The order of succession will be President, Vice President, Recording Secretary, Corresponding Secretary, Treasurer, Department Relations, and Alumni Relations.
Other elected positions will be set by the discretion of the incumbent executive council.
The officer immediately below the vacant office shall assume the duties of both offices until a replacement can be elected.

** Eligibility

Candidates for the executive offices must have served as an officer in the organization, unless no former officers are able and willing to fill this position.
Any vacancy in the offices of the Chapter shall be filled at the first regular meeting after the vacancy occurs, and when possible, before the vacancy occurs.

** Power Oversight

The President shall oversee the operations of the entirety of HKN.

The Vice President shall oversee the operations of the candidate process of HKN.

The Recording Secretary shall oversee the operations of the general HKN member body.

The Corresponding Secretary shall oversee the relations between the chapter and nationals.

The Treasurer shall oversee the operations of the HKN funds.

The Department Relations Officer shall oversee the relations between the chapter and the department and do Bridge Correspondent..

The Alumni Relations Officer shall oversee the relations between the chapter and alumni.

** Other Positions

As needed before elections, the Executive Committee may create or destroy other officer positions and shift duties correspondingly.

** Governance

The Executive Committee shall have the power to make decisions affecting the day-to-day operation of the chapter between regularly scheduled meetings.
The Executive Committee shall serve as a planning committee for activities throughout the semester and shall propose the initial agenda for all meetings.

** Quorum and Attendance

A quorum for transaction of business at an Executive Meeting shall be a two-thirds majority.
Executive committee meetings shall be open to all officers and members who wish to attend.
The Faculty Advisor(s) is invited to all Executive Meetings, but is not required to attend.

** Overturning Decisions

Decisions of the Executive Committee may be overturned by a two-thirds majority vote of the active members of the chapter.
